hashbang/shell-etc

- gemrc
- profile.d/user_ruby_bin_directory.sh
Lets users install gems with a plain `gem install` instead of having to specify `--user-install` manually or adding it to their `.gemrc` each.
> Configure rubygems to use --user-install by default

- gemrc
--bindir is the long form of -n, but apparently it breaks the gem env command.
> Use --bindir instead of -n in gemrc

- packages.txt
Apparently, the hashbang servers, as of this moment, lack installed CMake, as well as ncurses/ncursesw development packages (the libraries themselves, however, are installed).
> add cmake & libncurses dev packages

- .gitignore
- ssh/sshd_config
- use `UsePrivilegeSeparation sandbox`, which is more strict than `UsePrivilegeSeparation yes` during pre-auth;  
- allow using ed25519 for host keys;  
- remove a duplicate instance of `PasswordAuthentication yes`.
> Harden sshd_config

- packages.txt
This commit will add mc and mc-data, the packages required for Midnight Commander, to the list of packages to be installed.
> add midnight commander

- crontab
- man/man7/hashbang.7
- packages.txt
That utility displays the user a helpful message whenever they try to call a command that is unavailable, but could be installed from a package.
The cron job is there to ensure that the command-not-found database is kept up-to-date.
For instance:
```
% 7z
zsh: command not found: 7z
The program '7z' is currently not installed.  To run '7z' please ask your administrator to install the package 'p7zip-full'
7z: command not found
```
Debian's default `bash` configuration and the `zsh` config suggested in https://github.com/hashbang/dotfiles/pull/17 both support this.
> Install `command-not-found`

- man/man7/hashbang.7
- packages.txt
[Stow](https://www.gnu.org/software/stow/) is a symlink manager.
This is especially helpful to manage mixtures of local and system-wide installations.
> Add package stow

- apt/apt.conf.d/99defaultrelease
- apt/preferences
- apt/preferences.d/weechat
- apt/sources.list
- This needs to be reviewed carefully, as I started with fixing the pinning configuration (which was having no effect in its previous state).
- This can be deployed to a single shell server at first.
- No user disconnect is involved: they can use `/upgrade`.
> Fix apt pinning and bring weechat 1.3

- postfix/main.cf
- Relay mail through mail.#!.sh
This should help not getting our mail classified as SPAM
- Pin the relay's certificate and enforce use of strong crypto
- Refuse incoming mail that does not come from mail.hashbang.sh
- Do not let unprivileged users inspect or flush the mail queue
This depends on the merge and deployment of https://github.com/hashbang/docker-postfix/pull/3.
> postfix: Stricter configuration

- postfix/main.cf
Otherwise, mails meant for another @hashbang.sh user are not dispatched to mail.#! but delivered locally.
This makes the assumption that `mail.#!` rewrites recipients to `user@host.#!`, which is implemented in https://github.com/hashbang/docker-postfix/pull/5
As such, this depends on https://github.com/hashbang/docker-postfix/pull/5 being deployed.
> postfix: Only accept mail for the local host

- ssh/sshd_config
- This avoids to leave users wondering why SSH asks them for a password (when they don't have the key).
- This avoids admin's (or root's) passwords getting bruteforced.
- This kills of the insecure mechanism DSA.
> SSH: Usability & security improvements

- pam.d/common-account
- pam.d/common-auth
- pam.d/common-password
- pam.d/common-session
- pam.d/common-session-noninteractive
The autoconfig stopped handling our configuration due to “local changes” and using `sudo pam-auth-update --force` to trigger a regen produced a non-functional config (i.e. impossible to login anymore).
In light of this, it feels saner to switch to a hand-managed config and simplify it (since we aren't autogenerating it anymore).
> PAM: Drop Debian's autoconfig

- environment
- profile
- zsh/zprofile
The default environment had MAIL set for only bash, which might create problems with zsh users. I also fixed the umask to default to `077`
> fix umask and default environment

- ssh/sshd_config
This is useful in the context of hashbang/admin-tools#12 as it gives admins access to the root account in case of emergency.
I already deployed SSH keys for root (the admins') while testing hashbang/admin-tools#12
> ssh: Permit root login by pubkey only

- pam.d/common-session
- pam.d/common-session-noninteractive
- security/namespace.conf
- security/namespace.init
- tmpfiles.d/namespaces
- the unmnt_remnt option makes sudo switch to the destination user's namespace;
- `{/var,}/tmp` and `/run/{shm,lock}` are poly-instantiated on a per-user basis;
root gets to escape this and see all instances.
I have been fairly conservative, so this shouldn't break anything.
In particular, I would like (in a future patch) to:
- also poly-instantiate `/run/user`, and possibly more things in `/run`, as many services get rather dirty in there;
- ~~have a namespaced `/dev` which only allows access to pseudo-devices (`null`, `zero`, `random`, ...);~~
- enforce “read-onlyness” of the system files (equivalent to `systemd.exec`'s `ProtectSystem=full`);
- only make visible that user's home, to avoid issues like #11.
Also, I discussed with @lrvick the possibility of using network namespacing to …
> Compartment user sessions using pam_namespace

- sudoers
- Let `sudo` be called outside of a tty; this is required for Ansible SSH pipelining to work.
- Make `sudo` tickets valid for all open terminals of a given user.
> Sudo improvements

- rsyslog.conf
Now that systemd-journal is logging to persistant storage, we don't need rsyslog to do so as well.
After deploying, we can `rm /var/log/{auth.log,syslog,daemon.log,kern.log,lpr.log,mail.log,user.log,mail.info,mail.err,mail.warn,news.crit,news.err,news.notice,debug,messages}`
> Disable rsyslog logging to local files

- security/namespace.init
- Might want to consider using `ptmxmode=0644`.
- Consider use of a bind mount for /dev/pts instead of symlink.
Outside of user namespaces, we don't have a symlink from /dev/ptmx => /dev/ptmx/pts.
For information on `newinstance`, see the kernel docs: https://www.kernel.org/doc/Documentation/filesystems/devpts.txt
> Use newinstance option when mounting /dev/pts so that users can't see other ptys

- cron.hourly/fix-group-3000.sh
This should be reverted once no `gid 3000` processes are left (except from deleriux2; 3000 is their ID).
~~Also, `mkdir /var/log/fix-group-3000` before deploying.~~
> Temporary cronjob for fixing gid 3000 files

- luarocks/config-5.1.lua
- luarocks/config-5.2.lua
Adding `rocks_subdir` will version rocks, which makes lua5.1 sit more happily next to lua5.2.
However, it will require all users that have used luarocks to reinstall their rocks.
Added explicit paths for lua5.1 interpreter and includes.
> Fix luarocks configs

- apt/preferences.d/ansible
This should help making sure all admins have access to an Ansible 2 install, for hashbang/shell-etc#14.
> apt: Pull ansible from Stretch

- resolvconf/resolv.conf.d/tail
This lets relative hostnames, like `da1`, get resolved as `da1.hashbang.sh`, when the host exists.
> resolvconf: Set domain as hashbang.sh

- setup.sh
- Uses the cleaner way of handling the package set.
- Sets up `/etc` with correct file permissions.
- Do not setup SELinux (it was removed in #66).
- Correctly handles `grub`.
- Sets access rights that are consistent with what is currently deployed.
> setup.sh improvements

- postfix/main.cf
The default is 10MiB, this sets it to 50.
> Postfix: Increase max. message size

- etckeeper/commit.d/99push
- Passes an option to SSH to forbid prompting for a password
- Does not ignore push failures
> etckeeper: Do not prompt for password on push

- pam.d/common-session-noninteractive
- security/limits.conf
~~Given the urgency of this, I will take a lack of (dis)approval as an approval by timeout in 15h30 (2015-12-30, 11:00 UTC).~~
> Enforce per-user limits

- apt/sources.list
We were missing a security mirror for stretch, that's pretty bad.  :-(
This makes us use `deb.debian.org` as a mirror, which is (currently) backed by Fastly's CDN, and officially supported by Debian.
Unfortunately, it turns out that `httpredir.debian.org` is currently not actively maintained.
This should solve the “unreliable mirror” issues that @lrvick encountered.
> Use deb.debian.org as general-purpose & security mirror

- apt/preferences
This has caused too many issues, and I just replaced the last package that was pulling in stretch's `libstdc++6`, creating ABI breakage.
It is still possible to install things from `stretch`, by explicitely listing those packages in a pin.
The difference is that a package that doesn't exist in `jessie` or `jessie-backports` won't be silently installed from `stretch` anymore.
> apt: Never install silently from testing

- etckeeper/commit.d/99push
- etckeeper/etckeeper.conf
- sudoers
This makes `etckeeper` push to `git-infra.hashbang.sh`, on a dedicated branch.
Updates are still pulled from the `master` branch of `shell-etc`, on Github.
This impacts the admin's workflow as follows:
- Nothing changes when deploying updates pulled from `master`: as usual, just to `ansible-playbook shell.yml`.
- When dealing with on-server modifications (typically, security upgrades):
1. fetch the server branches from `git-infra.hashbang.sh` (`git fetch -a`);
2. review the changes (typically, did all the servers undergo the same change?);
3. do a signed merge into master: `git merge -S da1 ny1 sf1 to1`;
4. `push` to Github.
> etckeeper: Push to a dedicated branch

- etckeeper/push.d/99push
This will make it more convenient to update the state in `git-infra` when changes are pulled from `master` (i.e. add a call to `etckeeper push` in Ansible if new changes were received).
> etckeeper: Add `push` subcommand

- firejail/mutt.profile
This breaks a few bits of mutt config, for people who have a custom one...
> firejail: Allow mutt to read its own config

- sysctl.conf
Might reduce IRC lag issues that @ChickenNuggers encountered, and is a good practice anyhow.
That has been used in quite a few exploits.
> Sysctl tuning

- firejail/mutt.profile
- firejail/weechat.profile
- Enable R/O access to the home directory
- Enables R/W access to the maildirs
Thanks to @gmcclins for the report.
> Firejail fixup

- firejail/disable-common.inc
This makes the following directories read-only, that can be used to override executables or libs:
> Make user-writable ${PATH} and lib directories read-only

- sysctl.conf
This prevents other computers on the same LAN from defeating firewalling (or even reach services that only listen on localhost) by sending packets with spoofed source- and destination-address.
> sysctl: Enable reverse-path filtering

- nslcd.conf
- sssd/sssd.conf
The only process that uses any sort of LDAP credentials, `hashbangctl`, already used TLS.
However, the ability to compromise a server's view of `passwd` and `group` is very much a security issue.
> Use TLS to reach ldap.hashbang.sh

- systemd/journald.conf
- Retain at most 1 GB or 1 month of logs (whichever comes first)
- Do not retain `info` and `debug` messages. `notice` and lower log-level messages are kept.
> journald: Limit the amount of logs kept

- cron.daily/clean-lurkers
Previously, users between 1000 and 3000 were not concerned by `clean-lurkers`.  Moreover, system users between 60000 and 65533 would have been wrongly terminated.
The inclusion of the range 65535-4294967294 is for future-proofing, since userdb and Debian explicitely support it.
Lastly, this fixed some potential issues with quoting, and replaced a use of `awk` with `cut`.
> cron.daily/clean-lurkers: Proper user ranges

- systemd/system/crontab.target
- systemd/system/crontab@.service
- systemd/system/crontab@.timer
- systemd/system/crontab@day.service
- systemd/system/multi-user.target.wants/atd.service
- systemd/system/multi-user.target.wants/cron.service
- systemd/system/multi-user.target.wants/crontab.target
Those services can be used to run programs outside a user's slice, bypassing resources limits.
> systemd: Disable atd & cron

- man/man7/hashbang.7
Adding hashbangctl to the list of installed software would make it easier for new users to discover this tool.
> man: Add hashbangctl to software list in hashbang.7 man page

- pam.d/common-account
- pam.d/login
- pam.d/sshd
Without this change, user sessions may be started anyhow (eg. by systemd).
This was mildly annoying while deploying the fixes for #167
> pam.d: Uniformly enforce pam_nologin

- security/namespace.conf
This seems to be the root cause for the session persistence issues that users have been encountering on `ny1` and `sf1` (see #75); a reboot -- or at least, terminating all user sessions -- is required to deploy this, but session persistence is currently broken anyhow.
This is a hotfix, to be deployed tonight at midnight EST (04:00 UTC), so please review before then.
> Disable polyinstanciation for /dev

- msmtprc
```
sendmail: TLS certificate verification failed: the certificate fingerprint does not match
sendmail: could not send mail (account default from /etc/msmtprc)
```
> Update mail server fingerprint

- cron.daily/gpg-keyring
> cron.daily/gpg-keyring: Fixup (forgot an argument to trap(1))

- systemd/system/crontab@.timer
Previously, the targets weren't run due to a formatting error.
Following the documentation here[1], this change removes the cause of
the syntax error.
[1]: https://www.freedesktop.org/software/systemd/man/systemd.time.html
> systemd/system/crontab@.timer: Fix timing issues

- cron.daily/gpg-keyring
Commit 8535d26 introduced a bug when setting file permissions to `0644`
for the directory that the keyring is in. This fixes it by adding the
executable bits, so users can access files inside the directory.
> cron.daily/gpg-keyring: Fix permissions issues

- sudoers
Otherwise, when switching to a privileged user (say, root) to an unprivileged user (say, a malicious shell user), the later can obtain access to a pty that is attached to a root session, once sudo exits.
See [TtyPushbackPrivilegeEscalation](https://www.halfdog.net/Security/2012/TtyPushbackPrivilegeEscalation/) and [saltty](https://github.com/JeCodeAvecLeQ/saltty) for the kind of issues this prevents.
> sudo: Always allocate a new pseudo-terminal
